# Generated by Django 3.1.4 on 2021-01-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thebible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='img/user_profile_img/default.jpg', upload_to='img/user_profile_img/', verbose_name='프로필 사진')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='소개')),
                ('affiliation', models.CharField(blank=True, max_length=30, null=True, verbose_name='소속교단')),
                ('language', models.CharField(blank=True, max_length=30, null=True, verbose_name='언어')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='생성 시간')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유저 프로필',
                'verbose_name_plural': '유저 프로필',
                'db_table': 'UserProfile',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserLikeVerses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_time', models.DateTimeField(auto_now_add=True, verbose_name='저장 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebible.bibleverses')),
            ],
        ),
    ]
