# Generated by Django 3.1.4 on 2021-03-14 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thebible', '0003_auto_20210314_2251'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikeverses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikeverses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlikeverses',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlikeverses', to='thebible.bibleverses'),
        ),
    ]
