# Generated by Django 3.1.4 on 2021-01-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210117_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlikeverses',
            old_name='user_key',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlikeverses',
            old_name='verse_key',
            new_name='verse',
        ),
    ]
