# Generated by Django 3.1.4 on 2021-01-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleChapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.IntegerField(blank=True, null=True, verbose_name='장')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 시간')),
            ],
            options={
                'verbose_name': '성경 장',
                'verbose_name_plural': '성경 장',
                'db_table': 'BibleChapters',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BibleVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(choices=[(0, '개역개정'), (1, '개역한글'), (2, '공동번역'), (3, '새번역'), (4, '현대인'), (5, '简体'), (6, '繁体')], default=0, verbose_name='성경버전')),
                ('language', models.IntegerField(choices=[(0, 'korea'), (1, 'china')], default=0, verbose_name='성경언어')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 시간')),
            ],
            options={
                'verbose_name': '성경 버전',
                'verbose_name_plural': '성경 버전',
                'db_table': 'BibleVersions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_num', models.IntegerField(blank=True, null=True, verbose_name='절')),
                ('verse', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 시간')),
                ('BibleChapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebible.biblechapters')),
            ],
            options={
                'verbose_name': '성경 절',
                'verbose_name_plural': '성경 절',
                'db_table': 'BibleVerses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BibleTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_num', models.IntegerField(blank=True, null=True, verbose_name='제목넘버')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='제목')),
                ('title_type', models.IntegerField(choices=[(0, '구약'), (1, '신약'), (2, '旧约'), (3, '新约'), (4, '舊約'), (5, '新約')], default=0, verbose_name='타입')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 시간')),
                ('BibleVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebible.bibleversions')),
            ],
            options={
                'verbose_name': '성경 제목',
                'verbose_name_plural': '성경 제목',
                'db_table': 'BibleTitles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='biblechapters',
            name='BibleTitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thebible.bibletitles'),
        ),
    ]
