# Generated by Django 3.1.4 on 2021-01-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleverses',
            name='all_copy_count',
            field=models.IntegerField(default=0, verbose_name='누적 복사 회수'),
        ),
        migrations.AddField(
            model_name='bibleverses',
            name='all_like_count',
            field=models.IntegerField(default=0, verbose_name='누적 좋아요 회수'),
        ),
        migrations.AddField(
            model_name='bibleverses',
            name='now_like_count',
            field=models.IntegerField(default=0, verbose_name='현재 좋아요 회수'),
        ),
    ]
