# Generated by Django 3.1.4 on 2021-01-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thebible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드')),
                ('search_count', models.IntegerField(default=0, verbose_name='검색횟수')),
            ],
            options={
                'verbose_name': '키워드 정보',
                'verbose_name_plural': '키워드 정보',
                'db_table': 'KeywordsInfo',
                'ordering': ['-search_count'],
            },
        ),
        migrations.AddField(
            model_name='biblechapters',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='검색횟수'),
        ),
        migrations.AddField(
            model_name='bibletitles',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='검색횟수'),
        ),
        migrations.AddField(
            model_name='bibleversions',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='검색횟수'),
        ),
    ]
